### ISSUE TITLE
Проблема с config.xml

### ISSUE THREAD

**Issue by SuberSeb** [nawa/torrentmonitor-dockerized#17]
Наблюдаю странное поведение расширенных настроек TorrentMonitor (файл **config.xml**). Изменения, внесенные в этот файл, ни на что не влияют. Пробовал изменять его по всякому: в веб-интерфейсе и через docker cp. С помощью как раз docker cp выяснил, что изменения в него все-таки вносятся, но сам монитор полностью игнорирует данный файл. Похоже на проблему самого контейнера, так как TorrentMonitor, поставленный как веб-приложение, вполне нормально на этот файл реагирует и все работает.

**Comment by alfonder** [comment]
У меня тоже эти настройки не работают. Покажите, где работает нормально, я починю в контейнере.

**Comment by SuberSeb** [comment]
Если TorrentMonitor установить просто как веб-приложение, то все работает отлично.

**Comment by alfonder** [comment]
Все, починил. Можно качать имадж по тэгу v1.7.9-2
