### ISSUE TITLE
db file compromised

### ISSUE THREAD

**Issue by alfonder** [nawa/torrentmonitor-dockerized#3]
Knowing an URL, where TorrentMonitor runs, allows to get the DB file without a password.
Just open in browser: http://<tm_url>:<tm_port>/db/tm.sqlite and it downloads the DB file, which contains all the user's credentials.
Please, fix this vulnerability.

**Comment by nawa** [comment]
Cool bug :) I'll look on it

**Comment by alfonder** [comment]
Please, review the pull request with possible fix.
