### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by nightmare04** [nawa/torrentmonitor-dockerized#8]
Мне одному показалось или крон опять чудит? В процессах есть, однако ничего не происходит.

**Comment by nightmare04** [comment]
Разобрался, не запускался по причине отсутствия директории /data/logs/nginx исправьте пожалуйста.

**Comment by AlDemion** [comment]
Сори, мой косяк. Недоглядел когда правил пути к логам. Сделал пул реквест.

**Comment by nawa** [comment]
@nightmare04 Запушил образы - 1.5, latest
